CREATE USER '${WMS_STACK4_S1_CONF_USER}'@'%' IDENTIFIED BY '${WMS_STACK4_S1_CONF_PASSWORD}';
CREATE USER '${WMS_STACK4_S1_CONF_USER}'@'localhost' IDENTIFIED BY '${WMS_STACK4_S1_CONF_PASSWORD}';

GRANT ALL ON maxwell.* TO '${WMS_STACK4_S1_CONF_USER}'@'%';
GRANT ALL ON maxwell.* TO '${WMS_STACK4_S1_CONF_USER}'@'localhost';

GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO '${WMS_STACK4_S1_CONF_USER}'@'%';
GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO '${WMS_STACK4_S1_CONF_USER}'@'localhost';